apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/common
  - ../../../base/k8s-addons/nginx-ingress-controller
  - ../../../base/k8s-addons/metrics-server
  - ../../../base/monitoring/prometheus
  - ../../../base/monitoring/grafana