apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kibana
  namespace: argocd
spec:
  project: default
  source:
    chart: elastic/kibana
    repoURL: https://helm.elastic.co
    targetRevision: 8.5.1
    helm:
      releaseName: elastic/kibana
  destination:
    server: "https://kubernetes.default.svc"
    namespace: elk
  syncPolicy:
    automated: {}
#    syncOptions:
#      - CreateNamespace=true
