apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-ingress-controller
  namespace: argocd
spec:
  project: default
  source:
    chart: bitnami/nginx-ingress-controller
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 11.5.1
    helm:
      releaseName: nginx-ingress-controller
  destination:
    server: "https://kubernetes.default.svc"
    namespace: kube-system
  syncPolicy:
    automated: {}
