apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: elasticsearch
  namespace: argocd
spec:
  project: default
  source:
    chart: elasticsearch
    repoURL: https://helm.elastic.co
    targetRevision: 8.5.1
    helm:
      releaseName: elasticsearch
      values: |
        replicas: 2
        resources:
          requests:
            cpu: "900m"
            memory: "1Gi"
          limits:
            cpu: "900m"
            memory: "1Gi"
  destination:
    server: "https://kubernetes.default.svc"
    namespace: elk
  syncPolicy:
    automated: {}
#    syncOptions:
#      - CreateNamespace=true
